### ISSUE TITLE
iPod touch 7

### ISSUE THREAD

**Issue by xiaobai151** [itsnebulalol/ios15-tweaks#25]
Palera1n支持iPod touch 7越狱吗？

Does Palera1n support iPod touch 7 jailbreak?

**Comment by Parsa2820** [comment]
Since the processor is  checkm8 vulnerable (A10), it should be okay

**Comment by xiaobai151** [comment]
它有时显示找不到设备

Sometimes it display that it can't connect the device.

**Comment by Parsa2820** [comment]
Post your problem in palera1n discord 
https://dsc.gg/palera1n
