### ISSUE TITLE
also works on palera1n tweaks 

### ISSUE THREAD

**Issue by pwnd2e** [itsnebulalol/ios15-tweaks#5]
shortlook frontpage lastlook docksearch pulltorespring fiveicondock axon visum floatingdockpluss13/14 icleanerpro 

figured for u add to ur list

**Comment by pwnd2e** [comment]
https://user-images.githubusercontent.com/104146035/194710312-0fa84120-e8fd-43d1-8014-bff5246a1076.mov
![IMG_0018](https://user-images.githubusercontent.com/104146035/194710317-c8e7fdc4-53aa-4ae7-ab66-e280b056ba25.png)
![Uploading IMG_0020.png…]()


![Uploading IMG_0015.png…]()
![IMG_0001](https://user-images.githubusercontent.com/104146035/194710316-d152d24c-67f0-4f58-a38f-ae092ddb0863.jpeg)

**Comment by pwnd2e** [comment]
https://user-images.githubusercontent.com/104146035/194710375-b51752ae-22f2-4655-b3f5-82568605f85c.mov
![IMG_0015](https://user-images.githubusercontent.com/104146035/194710405-7cf7ebd2-2e90-478c-9e0d-71c752476626.png)
![IMG_0001](https://user-images.githubusercontent.com/104146035/194710414-d5dde014-a60d-442f-b150-9c1c4e5f63c5.jpeg)
![IMG_0018](https://user-images.githubusercontent.com/104146035/194710415-28a53c11-47dc-4ba2-8318-c3fc05011885.png)
![IMG_0020](https://user-images.githubusercontent.com/104146035/194710418-4daa5379-6e93-4bf8-aa71-09fd6982356f.png)

**Comment by pwnd2e** [comment]
pirates do it better with the pirated work lmao

**Comment by itsnebulalol** [comment]
Added most
